// Generated by CoffeeScript 1.4.0

/*
Author:
*/


/*
color data is present in the JSON feeds but each district is the same, so we assign unique values
*/


(function() {
  var $, $doc, $query, colors, create_gmap_latlng_from_coordinate_pairs, create_gmap_path, detail_zoom, district_contains_point, districts, do_map, downtown, find_district_by_point, geocoder, load_district_data, load_districts, make_region, map, mark_point, marker, region_contains_point, region_zoom, reject, reset_map;

  colors = {
    "DISTRICT 1": "#ABD9E9",
    "DISTRICT 2": "#FDAE61",
    "DISTRICT 3": "#2C7BB6",
    "DISTRICT 4": "#D7191C"
  };

  $ = jQuery;

  $doc = $(document);

  downtown = new google.maps.LatLng(33.214851, -97.133045);

  geocoder = new google.maps.Geocoder();

  region_zoom = 11;

  detail_zoom = region_zoom + 4;

  districts = {};

  /*
  the map object
  */


  map = null;

  /*
  marker, we only have one
  */


  marker = null;

  /*
  mimic ruby's reject method
  */


  reject = function(array, predicate) {
    var res, value, _i, _len;
    res = [];
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      value = array[_i];
      if (!predicate(value)) {
        res.push(value);
      }
    }
    return res;
  };

  /*
  take a string ex. -97.127557979037221,33.156515808050976
  split it into it's lat/lng component
  return a google LatLng object
  */


  create_gmap_latlng_from_coordinate_pairs = function(pair) {
    var parts;
    parts = pair.split(",");
    if (parts.length === !2) {
      console.log('data is malformed', pair);
    }
    return new google.maps.LatLng(parts[1], parts[0]);
  };

  /*
  */


  create_gmap_path = function(data) {
    var pair, _i, _len, _ref, _results;
    _ref = data.LinearRing.coordinates.split(" ");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pair = _ref[_i];
      _results.push(create_gmap_latlng_from_coordinate_pairs(pair));
    }
    return _results;
  };

  /*
  a district will have one outerBoundaryIs object
  a distrcit _may_ have an innerBoundaryIs array
  */


  make_region = function(data, district) {
    var inner, interior, interior_boundaries, paths, polygon, _i, _len;
    paths = [];
    paths.push(create_gmap_path(data.outerBoundaryIs));
    if (data.innerBoundaryIs) {
      interior_boundaries = (function() {
        var _i, _len, _ref, _results;
        _ref = data.innerBoundaryIs;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          inner = _ref[_i];
          _results.push(create_gmap_path(inner));
        }
        return _results;
      })();
    }
    if (interior_boundaries) {
      for (_i = 0, _len = interior_boundaries.length; _i < _len; _i++) {
        interior = interior_boundaries[_i];
        paths.push(interior);
      }
    }
    polygon = new google.maps.Polygon({
      paths: paths,
      strokeColor: colors[district],
      strokeWeight: 1,
      fillColor: colors[district],
      fillOpacity: 0.4,
      map: map
    });
    google.maps.event.addListener(polygon, 'click', function(event) {
      data = {
        latLng: event.latLng
      };
      return geocoder.geocode(data, function(results, status) {
        var address;
        if (status === google.maps.GeocoderStatus.OK) {
          console.log(status, results);
          if (results[0].types.indexOf('street_address') > -1) {
            address = results[0].formatted_address;
            $query.val(address);
            return mark_point(event.latLng, detail_zoom, address);
          } else {
            return mark_point(event.latLng, detail_zoom);
          }
        }
      });
    });
    return polygon;
  };

  /*
  grab JSON from the server for a district
  */


  load_district_data = function(district) {
    return $.getJSON("/content/themes/vote-denton/js/" + district + ".json", function(data, status) {
      /*
          district data, among other things, will contain:
          several polygons that encompass the boundaries
      */

      var district_data, district_name, regions;
      district_name = data.Placemark.ExtendedData.SchemaData.SimpleData[2]['#text'];
      if (data.Placemark.MultiGeometry.Polygon) {
        regions = (function() {
          var _i, _len, _ref, _results;
          _ref = data.Placemark.MultiGeometry.Polygon;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            district_data = _ref[_i];
            _results.push(make_region(district_data, district_name));
          }
          return _results;
        })();
      }
      return districts[district_name] = regions;
    });
  };

  /*
  */


  load_districts = function() {
    var district, _i, _len, _ref, _results;
    _ref = ["d1", "d2", "d3", "d4"];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      district = _ref[_i];
      _results.push(load_district_data(district));
    }
    return _results;
  };

  $doc.ready(load_districts);

  /*
  regions have an outer perimeter
  regions also have exclusion zones
  */


  region_contains_point = function(region, point) {
    if (region.Contains(point)) {
      return true;
    }
    return false;
  };

  /*
  districts have many regions
  */


  district_contains_point = function(district, region, point) {
    var foo, results;
    foo = (function() {
      var _i, _len, _ref, _results;
      _ref = districts[district];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        region = _ref[_i];
        _results.push(region_contains_point(region, point));
      }
      return _results;
    })();
    results = reject(foo, function(value) {
      return value === false;
    });
    if (results.length > 0) {
      return district;
    }
    return false;
  };

  find_district_by_point = function(point) {
    var district, final_district, foo, region, results;
    final_district = [];
    foo = (function() {
      var _results;
      _results = [];
      for (district in districts) {
        region = districts[district];
        _results.push(district_contains_point(district, region, point));
      }
      return _results;
    })();
    results = reject(foo, function(value) {
      return value === false;
    });
    if (results.length === !1) {
      return false;
    }
    return results[0];
  };

  /*
  given a location on the map, via address search or click
  show that location on the map
  */


  reset_map = function() {
    if (marker) {
      marker.setMap(null);
    }
    map.setCenter(downtown);
    return map.setZoom(region_zoom);
  };

  mark_point = function(point, zoom, address) {
    var district, infoWindow, marker_data, tmpl, tmplString;
    if (zoom == null) {
      zoom = detail_zoom;
    }
    if (address == null) {
      address = "Location";
    }
    district = find_district_by_point(point);
    map.setCenter(point);
    map.setZoom(detail_zoom);
    marker_data = {
      map: map,
      position: point
    };
    if (marker) {
      marker.setMap(null);
    }
    marker = new google.maps.Marker(marker_data);
    tmplString = "<p>{{=it.address}} is in Denton City {{=it.district}}</p>";
    tmpl = doT.template(tmplString);
    infoWindow = new google.maps.InfoWindow({
      content: tmpl({
        district: district,
        address: address
      })
    });
    return infoWindow.open(map, marker);
  };

  $query = $('#address');

  do_map = function() {
    var $button, $map, lookup_address, map_options;
    $button = $('#map-button');
    $map = $('#map-canvas');
    map_options = {
      zoom: region_zoom,
      center: downtown,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById('map-canvas'), map_options);
    google.maps.event.addListener(map, 'click', function() {
      reset_map();
      return $('#your_district').text("Location indicated doesn't appear to be part of a Denton city district. Please type in your address, or click on the map to find your district.");
    });
    lookup_address = function(event) {
      var data, geocode_success;
      event.preventDefault();
      data = {
        'address': $query.val() + " Denton TX"
      };
      geocode_success = function(results, status) {
        var address;
        address = results[0].formatted_address;
        $query.val(address);
        if (status === google.maps.GeocoderStatus.OK) {
          return mark_point(results[0].geometry.location, detail_zoom, address);
        } else {
          return reset_map();
        }
      };
      return geocoder.geocode(data, geocode_success);
    };
    return $button.click(lookup_address);
  };

  $doc.ready(do_map);

}).call(this);
